// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/captcha": {
            "get": {
                "description": "存储并发送验证码接口",
                "tags": [
                    "用户模块"
                ],
                "summary": "存储并发送验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/captcha/verify": {
            "get": {
                "description": "验证验验证码接口",
                "tags": [
                    "用户模块"
                ],
                "summary": "验证验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户输入的验证码",
                        "name": "ucode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/room/appointment": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "预约自习室接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "自习室模块"
                ],
                "summary": "预约自习室",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AppointmentDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/room/show": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "自习室查看接口",
                "tags": [
                    "自习室模块"
                ],
                "summary": "查看自习室状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "自习室id",
                        "name": "room_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/room/showAppointment": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "预约自习室接口",
                "tags": [
                    "自习室模块"
                ],
                "summary": "查看预约自习室",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/room/showIdle": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "自习室查看接口",
                "tags": [
                    "自习室模块"
                ],
                "summary": "查看自空闲习室",
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/user/checkInfo": {
            "get": {
                "description": "查看用户信息接口",
                "tags": [
                    "用户模块"
                ],
                "summary": "查看用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/user/logoff": {
            "get": {
                "description": "用户注销接口",
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注销",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "用户注册接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRegisterDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/api/user/setAvatar": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "设置用户头像接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "设置用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UploadResp"
                        }
                    }
                }
            }
        },
        "/api/user/setInfo": {
            "post": {
                "description": "设置用户信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "设置用户信息",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserInfoDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/test/captcha": {
            "get": {
                "description": "获取验证码接口",
                "tags": [
                    "测试模块"
                ],
                "summary": "获取验证码",
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        },
        "/test/captcha/verify": {
            "get": {
                "description": "验证验验证码接口",
                "tags": [
                    "测试模块"
                ],
                "summary": "验证验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户输入的验证码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务代码",
                        "schema": {
                            "$ref": "#/definitions/result.CodeResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AppointmentDto": {
            "type": "object",
            "properties": {
                "room_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UserInfoDto": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                },
                "stu_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UserLoginDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.UserRegisterDto": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "result.CodeResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码，0=成功，非0=错误",
                    "type": "integer",
                    "example": 0
                },
                "msg": {
                    "description": "可读提示",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "user.UploadResp": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
