definitions:
  dto.UserLoginDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.UserRegisterDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  result.CodeResp:
    properties:
      code:
        description: 业务码，0=成功，非0=错误
        example: 0
        type: integer
      msg:
        description: 可读提示
        example: success
        type: string
    type: object
info:
  contact: {}
paths:
  /api/room/show:
    get:
      description: 自习室查看接口
      parameters:
      - description: 自习室id
        in: query
        name: room_id
        required: true
        type: integer
      responses:
        "200":
          description: 业务代码
          schema:
            $ref: '#/definitions/result.CodeResp'
      summary: 查看自习室状态
      tags:
      - 自习室模块
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: 业务代码
          schema:
            $ref: '#/definitions/result.CodeResp'
      summary: 用户登录
      tags:
      - 用户模块
  /api/user/logoff:
    get:
      description: 用户注销接口
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: 业务代码
          schema:
            $ref: '#/definitions/result.CodeResp'
      summary: 用户注销
      tags:
      - 用户模块
  /api/user/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterDto'
      produces:
      - application/json
      responses:
        "200":
          description: 业务代码
          schema:
            $ref: '#/definitions/result.CodeResp'
      summary: 用户注册
      tags:
      - 用户模块
swagger: "2.0"
